# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out
        uses: actions/checkout@v2
      
      # 使用 Rsync 同步文件
      - name: RSyncer Action
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.WORKFLOW_ACTION_TOKEN }}
        with:
          flags: '-avzr --delete'
          src: './public/'
          dest: '${{ secrets.ALIYUN_HK187_WEBSITE_USER }}@${{ secrets.ALIYUN_HK187_HOST }}:${{ secrets.ALIYUN_HK187_WEBSITE_PATH }}'
          

      # 使用 SSH 链接远程服务器
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.ALIYUN_HK187_HOST }}
          username: ${{ secrets.ALIYUN_HK187_WEBSITE_USER }}
          password: ${{ secrets.ALIYUN_HK187_WEBSITE_PASSWORD }}
          source: "./public"
          # target: ${{ secrets.ALIYUN_HK187_WEBSITE_PATH }}
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
